image: maven:latest

stages:
    - build
    - test
    - deploy
Build:
    stage: build
    tags:
        - dalfcs_docker_autoscale
    script:
        - cd BackEnd
        - mvn clean package -DskipTests
        
Test:
    stage: test
    tags:
        - dalfcs_docker_autoscale
    script:
        - cd BackEnd
        - mvn clean verify

deploy-job:
    stage: deploy
    script:
        echo "Application successfully deployed."
